-- -- Hack to show Splash screen + file tree... 
-- vim.api.nvim_create_autocmd("VimEnter", {
--     callback = function()
--         local is_no_file = vim.fn.argc() == 0
--         local is_dir = vim.fn.argc() == 1 and vim.fn.argv(0) == "NvimTree_1"
--         vim.cmd("NvimTreeClose")
--         if is_no_file or is_dir then
--             vim.cmd("Startup display")
--             vim.cmd("NvimTreeToggle")
--         else
--             vim.cmd("NvimTreeToggle")
--         end
--         vim.cmd("wincmd l")
--     end,
-- })
--
--
-- vim.api.nvim_create_autocmd("TabLeave", {
--     callback = function ()
--         vim.cmd("wincmd l")
--     end,
-- })
--
-- -- Hack to Open filetree on newtab 
-- vim.api.nvim_create_autocmd("TabNewEntered", {
--     callback = function ()
--         vim.cmd("NvimTreeClose")
--         vim.cmd("NvimTreeToggle")
--         vim.cmd("wincmd l")
--     end,
-- })
--
-- vim.api.nvim_create_autocmd("", {
--     nested = true,
--     callback = function()
--         local buffers = vim.api.nvim_list_bufs()
--         for _, buf in ipairs(buffers) do
--         local buf_name = vim.api.nvim_buf_get_name(buf)
--         print(buf_name)
--          end
--     end
-- })
